package(default_visibility = ["//visibility:public"])

cc_library(
    name = "thread_annotations",
    hdrs = ["thread_annotations.h"],
    alwayslink = 1,
)

cc_library(
    name = "mutex_impl",
    hdrs = ["mutex_impl.h"],
)
