package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test_main",
    srcs = ["test_main.cc"],
    deps = [
        "//base:init_ghost",
        "@gtest//:gtest_main",
    ],
)
